### ISSUE TITLE
After updating to version 0.2.7 whe encountred the following Class Alma\MonthlyPayments\Helpers\ApiConfigHelper does not exist

### ISSUE THREAD

**Issue by gharbi-mohamed** [alma/alma-monthlypayments-magento2-graph-ql#3]
After updating to version 0.2.7 whe encountred the following error when 

`bin/magento setup:di:compile`

 Class Alma\MonthlyPayments\Helpers\ApiConfigHelper does not exist            
  Class Alma\GraphQL\Model\Resolver\AlmaConfig\Interceptor generation error:   
  The requested class did not generate properly, because the 'generated' dire  
  ctory permission is read-only. If --- after running the 'bin/magento setup:  
  di:compile' CLI command when the 'generated' directory permission is set to  
   write --- the requested class did not generate properly, then you must add  
   the generated class object to the signature of the related construct metho 

This is related to the fact that the alma-monthlypayments-magento2 release is not updated with the latest modifications considered on graphql

**Comment by Francois-Gomis** [comment]
hi,
version 0.2.7 isn't yet on packagist : https://packagist.org/packages/alma/alma-monthlypayments-magento2-graph-ql
I don't know why they have a tag v0.2.7 on the Merge commit, i will delete it. 
In the next version, the required version of "alma/alma-monthlypayments-magento2" will be changed.

Thank.

**Comment by syjust-alma** [comment]
I published a `v0.3.0` for packagist

**Comment by Francois-Gomis** [comment]
@gharbi-mohamed  New release with good dependency is online.

Best regards.
