### ISSUE TITLE
This package required an abandonned package

### ISSUE THREAD

**Issue by xaviermarchegay** [alma/alma-monthlypayments-magento2-graph-ql#5]
We want to use the new Magento 2 package (https://github.com/alma/alma-monthlypayments-magento2) but this repository still requires the old package.

https://github.com/alma/alma-monthlypayments-magento2-graph-ql/blob/af661c3bb20d4b41ea389e7dcb7ecdc96d37c7c4/composer.json#L6

Source: https://packagist.org/packages/alma/alma-monthlypayment

It is possible to update this package to require the new magento 2 module ?

Thanks

**Comment by Francois-Gomis** [comment]
Hi,
thanks for your feedback.
The new version of the plugin is comming soon with the fix.
